### ISSUE TITLE
At one point it just started to crash!

### ISSUE THREAD

**Issue by echocage123** [SPCodeOrg/SPCode#124]
1
Section: SPCODE MAIN
.NET Version: 4.0.30319.42000
Is local installation?: True
OS: Microsoft Windows NT 6.2.9200.0
64 bit OS: TRUE
64 bit mode: TRUE
Dir: C:\Users\user\AppData\Roaming\spcode
Working Set: 178236 kb
Installed UI Culture: ru-RU
Current UI Culture: en-US
Current Culture: en-US

Exception 1
Message:
The given path's format is not supported.
Stacktrace:
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at SPCode.UI.MainWindow.<ErrorResultGrid_SelectionChanged>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at SPCode.Program.Main(String[] args)
Source:
mscorlib
HResult Code:
-2146233067
Helplink:
null
Targetsite Name:
EmulateFileIOPermissionChecks

**Comment by maxijabase** [comment]
Can you reproduce this, or program doesn't open anymore? Are you in stable or in beta?

**Comment by echocage123** [comment]
Yes, I can reproduce it, but I don't know what version I have

**Comment by maxijabase** [comment]
Can you give steps of reproduction and send a screnshot of the About Window Located in Tools -> About?
![image](https://user-images.githubusercontent.com/20617661/182049146-2cc0ef8f-d57a-44b4-b0e9-8d98331a4983.png)

**Comment by echocage123** [comment]
Ahah. I created this issue because my program does not start! After opening, I get an error message saved in /crashlogs for seconds

**Comment by maxijabase** [comment]
Go to your installation directory and rename the `options_0.dat` file to allow the program to boot up again and follow the steps I described so I can help you.

**Comment by echocage123** [comment]
i dont have it
![image](https://user-images.githubusercontent.com/67440446/183991887-118b5758-38c6-4b3e-b7f3-70900b887fe4.png)

**Comment by echocage123** [comment]
I have already reinstalled the program 2 times

**Comment by echocage123** [comment]
It was 1.8.1.0 version

**Comment by maxijabase** [comment]
You don't have it because it doesn't get created if the program has never been opened since it was installed. After reinstalling, does it open normally?

**Comment by maxijabase** [comment]
Can you give me the full route name of the file you're trying to open in SPCode? Also, try the beta version and see if it crashes. https://github.com/SPCodeOrg/SPCode/releases/tag/1.8.1.1.beta1190

**Comment by echocage123** [comment]
dude, i just open spcode, not specific file. Can you just tell me what I need to do so that I can run the program normally?

**Comment by echocage123** [comment]
LOL! Bets isn`t crashing. Victory! Thanks

**Comment by maxijabase** [comment]
You told me you could reproduce it but you didn't tell me how, so you don't know after all. I had the suspicion it could have to do with the route name of a file you tried to open but you didn't tell me because you don't know how to reproduce the bug. I told you to tell me the program version with specific instructions alongside screenshots and you took 4 comments and 10 days to tell me that. I told you what to do to make the program boot normally and you didn't do it. And when you solved it you didn't explain what you did so whoever gets the same error again probably won't be able to sort it out because you didn't cooperate to solve it. Next time stop rushing and read what is being told to you so you don't waste anyone's time anymore.

**Comment by maxijabase** [comment]
Next time follow what people prepare to help you solve the issue.
![image](https://user-images.githubusercontent.com/20617661/185975431-bcc5a576-8c19-4623-bd58-ef839837e78a.png)
